version: 2.1

orbs:
  serverless: circleci/serverless-framework@1.0.1
  aws-cli: circleci/aws-cli@1.0.0

jobs:
  build-and-test:
    executor:
      name: serverless/default
    steps:
      - checkout
      - aws-cli/setup:
          configure-default-region: false
      - serverless/setup
      - run:
          name: install
          command: | 
                cd ./server
                npm ci
      - run:
          name: deploy
          command: |
                cd ./server
                serverless deploy -v

workflows:
  build-and-test:
    jobs:
      - build-and-test:
          context: aws-playground
